version: '3.6'

services:
  postgres:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres-data:
