version: '3.6'

services:
  sbt:
    build:
      context: .
      dockerfile: sbt.Dockerfile
    volumes:
      - ./code:/code
    tty: true
    ports:
      - 9000:9000

  postgres:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres-data: